In [1]:
import numpy as np

1. How to Creating a 3x3 Identity Matrix with Float Data Type?

In [2]:
a=np.array([[[1,2,3],[4,5,6]]],dtype=float)
a
# a.ndim

array([[[1., 2., 3.],
        [4., 5., 6.]]])

 2. Create a 1D Array with Random Values between 0 and 1.

In [3]:
a2=np.random.uniform(0,1,10)
a2

array([0.24948848, 0.98328944, 0.30732862, 0.11910243, 0.48553819,
       0.77331439, 0.83387252, 0.10744953, 0.88778665, 0.44796156])

 3. Create a 2D Array with Random Integer Values.

In [4]:
a3=np.random.randint(10,20,size=(3,4))
a3

array([[13, 10, 10, 10],
       [16, 14, 18, 10],
       [19, 18, 15, 12]])

4. Creating an Array Using a Custom Function.


In [5]:
def my_function(x,y):
  return x*y
a4=np.fromfunction(my_function,(3,3),dtype=int)
a4

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

5. Reshaping a 1D Array into a 2D Array


In [6]:
a5=np.array([10,20,30,40,50,60])
a=a5.reshape(2,3)
a
# a.ndim
# a5.ndim

array([[10, 20, 30],
       [40, 50, 60]])

6.How to Creating a 3x3 Array of Ones?


In [7]:
a6=np.ones(9,dtype=int).reshape(3,3)
a6

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

7. How to get the common items between two pythons
NumPy?

  Input:
  a = np. array ([1,2,3,2,3,4,3,4,5,6])
  b = np. array ([7,2,10,2,7,4,9,4,9,8])
  Expected Output:
  array ([2, 4])

In [8]:
a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])

#using intersect1d we can get the common values from both array and output
a7=np.intersect1d(a,b)
a7

array([2, 4])

8. From array a remove all items present in
  array b Input:
  a = np. array ([1,2,3,4,5])
  b = np. array ([5,6,7,8,9])
  Expected Output:
  array ([1,2,3,4])

In [9]:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])
a2=np.setdiff1d(a,b)
a2

array([1, 2, 3, 4])

9. Limit the number of items printed in python NumPy array a to a maximum of
6 elements.
a = np. arrange (15)
Expected Output:
array ([ 0, 1, 2, ..., 12, 13, 14]

In [10]:
a9=np.arange(15)
np.set_printoptions(threshold=6)
a9

array([ 0,  1,  2, ..., 12, 13, 14])

10. Drop all nan values from a 1D NumPy
array Input:
np. array ([1,2,3, np.nan,5,6,7, np.nan])
Desired Output:
array ([ 1., 2., 3., 5., 6., 7.])

In [11]:
a10=np.array ([1,2,3, np.nan,5,6,7, np.nan])
a10=np.nan_to_num(a10)
a10

array([1., 2., 3., ..., 6., 7., 0.])

11. Question: Create a 1D NumPy array of the first 20 natural numbers and a
2D NumPy array of shape (4, 5) with values ranging from 1 to 20.

In [12]:
#1D aaray
a11=np.arange(1,21)
print(a11)

#2D array
a12=np.arange(1,21).reshape(4,5)
a12

[ 1  2  3 ... 18 19 20]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

12. Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size,
number of dimensions, and data type. Change its data type to float64 and verify
the change.

In [13]:
a12=np.arange(24).reshape(2,3,4)
a12
print("Shape of the Array::",a12.shape)
print("Size of the Array::",a12.size)

print("Number of dimension of Array::",a12.ndim)
print("Currunt datatype of the Array::",a12.dtype)

#conver the datatype int to float
a12=np.arange(24,dtype=float).reshape(2,3,4)

#astype(np.float64)
print("After Conver the datatype of the Array::",a12.dtype)

Shape of the Array:: (2, 3, 4)
Size of the Array:: 24
Number of dimension of Array:: 3
Currunt datatype of the Array:: int64
After Conver the datatype of the Array:: float64


13. Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then
flatten it back into a 1D array using ravel (). Verify that the flattened array
matches the original.

In [14]:
a13=np.arange(12)
print("1D Array::-",a13)
print("******************")
a13=np.arange(12).reshape(3,4)
print("2D Array::-\n",a13)
print("******************")
print("Back into 1D Array using reval::-",a13.ravel())
np.array_equal(a13,a13)

1D Array::- [ 0  1  2 ...  9 10 11]
******************
2D Array::-
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
******************
Back into 1D Array using reval::- [ 0  1  2 ...  9 10 11]


True

14. Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4,
5, 6]), perform element-wise addition, subtraction, multiplication, and
division. Explain the behavior when dividing by zero.

In [15]:
a = np. array ([1, 2, 3])
b = np. array ([4, 5, 6])

print("Addition of A and B::-",a+b)
print("Subtraction of A and B::-",a-b)
print("Multiplication of A and B::-",a*b)
print("Division of A and B::-",a/b)
print("**************")

#Explain the behavior when dividing by zero.

b1=np.array([1,0,2])
print("Division of A and B1::-",a/b1)
# it's give a RuntimeWarning: divide by zero encountered in divide
# if we divide a nonzero number by zero gives an inf(infinity) as an output([1.  inf 1.5])

Addition of A and B::- [5 7 9]
Subtraction of A and B::- [-3 -3 -3]
Multiplication of A and B::- [ 4 10 18]
Division of A and B::- [0.25 0.4  0.5 ]
**************
Division of A and B1::- [1.  inf 1.5]


/tmp/ipython-input-1926495648.py:13: RuntimeWarning: divide by zero encountered in divide
  print("Division of A and B1::-",a/b1)


15. Question: Create a 2D array of shape (3, 1) and a 1D array of length 3. Perform
element-wise addition using broadcasting. Explain how broadcasting rules apply
in this scenario.

In [16]:
x=np.arange(3).reshape(3,1)
y=np.array([1,2,3])

print("Shape of the X Dimension is::-",x.shape)
print("Shape of the Y Dimension is::-",y.shape)

print("X is 2D Array::-\n",x)
print("Y is 1D Array::-\n",y)

print("Dimension of X Array is::-",x.ndim)
print("Dimension of Y Array is::-",y.ndim)

print("Addition of X and Y::-\n",x+y)


#Explain how broadcasting rules apply in this scenario.
# only apply on 1d array and either rows or column should be same.
# Here There is Y is 1D array and y demension shape is (3,) so it's consider as (1,3) for Broadcasting

Shape of the X Dimension is::- (3, 1)
Shape of the Y Dimension is::- (3,)
X is 2D Array::-
 [[0]
 [1]
 [2]]
Y is 1D Array::-
 [1 2 3]
Dimension of X Array is::- 2
Dimension of Y Array is::- 1
Addition of X and Y::-
 [[1 2 3]
 [2 3 4]
 [3 4 5]]


16. Question: Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying elements greater than 5. Replace all elements greater than 5 with the value 5.

In [17]:
a16=np.random.randint(0,10,12).reshape(3,4)
print("Random number between 0 to 10::-\n",a16)

mask=a16>5
print("identifying elements greater than 5::-\n",mask)

a16[mask]=5
print("Replace all elements greater than 5 with the value 5::-\n",a16)

Random number between 0 to 10::-
 [[7 8 5 1]
 [7 8 3 4]
 [3 5 7 7]]
identifying elements greater than 5::-
 [[ True  True False False]
 [ True  True False False]
 [False False  True  True]]
Replace all elements greater than 5 with the value 5::-
 [[5 5 5 1]
 [5 5 3 4]
 [3 5 5 5]]


17. Question: Given a 4x4 array of random integers, use indexing and slicing
to extract:


o The entire second row

o The last column

o The subarray consisting of the first two rows and first two columns

In [18]:
a17=np.random.randint(0,20,16).reshape(4,4)
print("Random integers of 4*4 Array::-\n",a17)

#Using Indexing to Extract the elements:
print("The entire second row::-",a17[1,:])
print("The last column::-",a17[3,:])
print("The subarray consisting of the first two rows and first two columns::-\n",a17[:2,:2])

print("****************************************************************************")
#Using Slicing to Extract the elements:
print("The entire second row::-",a17[1:2])
print("The last column::-",a17[-1:])
print("The subarray consisting of the first two rows and first two columns::-\n",a17[0:2,0:2])



Random integers of 4*4 Array::-
 [[ 8 15 10  9]
 [ 0 18  2 16]
 [17 19 12 19]
 [ 7  2  7 18]]
The entire second row::- [ 0 18  2 16]
The last column::- [ 7  2  7 18]
The subarray consisting of the first two rows and first two columns::-
 [[ 8 15]
 [ 0 18]]
****************************************************************************
The entire second row::- [[ 0 18  2 16]]
The last column::- [[ 7  2  7 18]]
The subarray consisting of the first two rows and first two columns::-
 [[ 8 15]
 [ 0 18]]


18. Question: Describe a practical example where NumPy can be used in EDA,
AI, ML, and DL, and implement a NumPy solution for a simple task in each
area.

In [19]:

# Sample sales data
sales = np.array([250, 300, 400, 350, 500, 450])

print("EDA Example:")
print("Mean Sales:", np.mean(sales))
print("Median Sales:", np.median(sales))
print("Standard Deviation:", np.std(sales))


# Random weight initialization between -1 and 1
weights = np.random.randint(-1, 1,9).reshape(3,3)
print("\nAI Example:")
print("Initial Weights:\n", weights)


# Input vector and weights
inputs = np.array([0.5, 0.8, 0.2])
weights = np.array([
    [0.2, 0.4, 0.6],
    [0.5, 0.7, 0.9],
    [0.1, 0.3, 0.5]
])

# Forward pass calculation
output = np.dot(inputs, weights)

print("\nDL Example:")
print("Output after forward pass:", output)


# Sample feature values
features = np.array([10, 20, 30, 40, 50])
normalized = (features - np.min(features)) / (np.max(features) - np.min(features))

print("\nML Example:")
print("Normalized Features:", normalized)


EDA Example:
Mean Sales: 375.0
Median Sales: 375.0
Standard Deviation: 85.39125638299666

AI Example:
Initial Weights:
 [[ 0  0  0]
 [-1 -1 -1]
 [ 0  0 -1]]

DL Example:
Output after forward pass: [0.52 0.82 1.12]

ML Example:
Normalized Features: [0.   0.25 0.5  0.75 1.  ]


19. Question: Create a random 4x4 matrix and use NumPy to compute its
eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the
matrix.

In [28]:
import numpy as np

# Create random 4x4 matrix
np.random.seed(42)
A = np.random.rand(4, 4)

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Reconstruct matrix
Lambda = np.diag(eigenvalues)
A_reconstructed = eigenvectors @ Lambda @ np.linalg.inv(eigenvectors)

# Verify
print("Original Matrix:\n", A)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)
print("\nReconstructed Matrix:\n", A_reconstructed)
print("\nVerification:", np.allclose(A, A_reconstructed))


Original Matrix:
 [[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497 0.18340451]]

Eigenvalues:
 [ 1.83720612+0.j         -0.39432133+0.55229552j -0.39432133-0.55229552j
 -0.31403981+0.j        ]

Eigenvectors:
 [[ 0.64723702+0.j          0.58357969+0.j          0.58357969-0.j
  -0.18805166+0.j        ]
 [ 0.29851455+0.j         -0.25203329+0.49664672j -0.25203329-0.49664672j
  -0.60580025+0.j        ]
 [ 0.55766099+0.j         -0.07578653+0.19548415j -0.07578653-0.19548415j
   0.70586228+0.j        ]
 [ 0.4254263 +0.j         -0.25658199-0.48935063j -0.25658199+0.48935063j
   0.31527935+0.j        ]]

Reconstructed Matrix:
 [[0.37454012-7.29090257e-17j 0.95071431-1.33340074e-16j
  0.73199394+3.50581434e-17j 0.59865848+3.09976655e-17j]
 [0.15601864+3.07479745e-17j 0.15599452-7.20098652e-17j
  0.05808361-1.96458082e-17j 0.86617615+5.12933652e-18j]
 [0.60111501-9.1

20. Question: Create a 1D array of 27 elements and reshape it into a 3x3x3
3D array. Flatten it back into a 1D array and compare the flattened array
with the original.

In [20]:
a20=np.arange(27)
print("1D Array::-\n",a20)
print("Dimension of Array::-",a20.ndim)
a20=np.arange(27).reshape(3,3,3)
print("Reshape into 3x3x3 3D array::-\n",a20)
print("Dimension of Array::-",a20.ndim)
print("Flatten it back into a 1D array:-\n",a20.ravel())
np.array_equal(a20,a20)


1D Array::-
 [ 0  1  2 ... 24 25 26]
Dimension of Array::- 1
Reshape into 3x3x3 3D array::-
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
Dimension of Array::- 3
Flatten it back into a 1D array:-
 [ 0  1  2 ... 24 25 26]


True

21. Question: Perform matrix multiplication of two 2D arrays using np.dot ()
and @. Compare the results and performance of both methods using a large
dataset.

In [21]:
import numpy as np
import time

# Step 1: Create two large random 2D arrays
a = np.random.randint(1, 10, (1000, 1000))
b = np.random.randint(1, 10, (1000, 1000))

# Step 2: Matrix multiplication using np.dot()
start_time = time.time()
result_dot = np.dot(a, b)
time_dot = time.time() - start_time
print("Time using np.dot():", time_dot)

# Step 3: Matrix multiplication using @ operator
start_time = time.time()
result_at = a @ b
time_at = time.time() - start_time
print("Time using @ operator:", time_at)

# Step 4: Verify both results are same
print("Results are equal:", np.array_equal(result_dot, result_at))


Time using np.dot(): 1.390674352645874
Time using @ operator: 1.4464168548583984
Results are equal: True


22. Question: Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4,
1). Perform an element-wise operation using broadcasting and explain the
result. Use np. new axis to achieve the same result without broadcasting.

In [22]:
x1=np.arange(8).reshape(2,1,4)
print("X1 is 3D Array::-\n",x1)
x2=np.arange(4).reshape(4,1)
print("X2 is 2D Array::-\n",x2)
result = x1 + x2.T[np.newaxis, :, :]  # Now shapes match: (2, 1, 4) + (1, 4, 1)
print("Addition of X1 and X2::-\n", result)

X1 is 3D Array::-
 [[[0 1 2 3]]

 [[4 5 6 7]]]
X2 is 2D Array::-
 [[0]
 [1]
 [2]
 [3]]
Addition of X1 and X2::-
 [[[ 0  2  4  6]]

 [[ 4  6  8 10]]]


23. Question: Generate a 2D array of random floats between 0 and 1. Use
conditional operators to create a Boolean mask for values less than 0.5.
Replace these values with their squares and leave the rest unchanged.

In [23]:
a1=np.random.uniform(0,1,30).reshape(30)
print("2D array of random floats between 0 and 1::-\n",a1)


mask=a1<.05
print("\n mask for values less than 0.5::-\n",mask)

a1[mask]**2
print("\nReplace these values with their squares and leave the rest unchanged::-\n",a1)

2D array of random floats between 0 and 1::-
 [0.33133116 0.20675619 0.40772082 ... 0.72532157 0.58955982 0.61371641]

 mask for values less than 0.5::-
 [False False False ... False False False]

Replace these values with their squares and leave the rest unchanged::-
 [0.33133116 0.20675619 0.40772082 ... 0.72532157 0.58955982 0.61371641]


24. Question: Given a 5x5 array of sequential integers, use slicing to:

o Extract the diagonal elements

o Replace the elements of the middle row with zeros

o Flip the array vertically and horizontally

In [24]:
a24=np.arange(25).reshape(5,5)
print("5x5 array::-\n",a24)

a=a24[np.arange(5),np.arange(5)]
print("\nExtract the diagonal elements::-\n",a)

a24[2,:]=0
print("\nReplace the elements of the middle row with zeros::-\n",a24)

print("\nFlip the array vertically::-\n",a24[::-1])
print("\nFlip the array horizontally::-\n",a24[:,::-1])

print("\n")
np.fliplr(a24)# we can also flip the horizontally array using flipr

5x5 array::-
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Extract the diagonal elements::-
 [ 0  6 12 18 24]

Replace the elements of the middle row with zeros::-
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [ 0  0  0  0  0]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Flip the array vertically::-
 [[20 21 22 23 24]
 [15 16 17 18 19]
 [ 0  0  0  0  0]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]

Flip the array horizontally::-
 [[ 4  3  2  1  0]
 [ 9  8  7  6  5]
 [ 0  0  0  0  0]
 [19 18 17 16 15]
 [24 23 22 21 20]]




array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [ 0,  0,  0,  0,  0],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20]])

25. Question: Create a 4D array of shape (2, 3, 4, 5) with random integers.
Use advanced slicing to extract a subarray and compute the mean along a
specified axis.

In [25]:
a=np.random.randint(1,115,120).reshape(2,3,4,5)
print(a)
subarray = a[0, :, :2, 1:4]
print("\nSubarray shape:", subarray.shape)
print(subarray)

# Step 3: Compute mean along a specific axis
# Example: Mean along last axis (-1)
mean_values = np.mean(subarray, axis=-1)
print("\nMean along last axis:\n", mean_values)

[[[[ 77   2 107  33  20]
   [ 84  48  61   1 107]
   [ 10  41  47  87  81]
   [ 66  73  28  94  45]]

  [[ 79  49  39 111 109]
   [ 33  46  39  17  33]
   [113 112  67  57  43]
   [ 10   2   8  67  85]]

  [[ 25  78  13  38  17]
   [  3  17  27  74  77]
   [ 94  83  38  91  55]
   [ 91  34 113  74  39]]]


 [[[ 66  82  66  73  81]
   [ 15  50 100  10  73]
   [ 58  38  19  55 107]
   [108  47  84  30 113]]

  [[ 55  75   6 105  52]
   [  9  36  98  91 110]
   [ 17  61  64  78  31]
   [ 46  10  91 106  78]]

  [[ 40  46 105  93  58]
   [ 76  96  95  31  73]
   [ 35  71  56  94  56]
   [ 86  60   5  75  87]]]]

Subarray shape: (3, 2, 3)
[[[  2 107  33]
  [ 48  61   1]]

 [[ 49  39 111]
  [ 46  39  17]]

 [[ 78  13  38]
  [ 17  27  74]]]

Mean along last axis:
 [[47.33333333 36.66666667]
 [66.33333333 34.        ]
 [43.         39.33333333]]


26. Question: Given an array of shape (10, 20), reshape it to (20, 10) and (5,
40). Discuss the impact on the array's shape, size, and dimensionality.

In [26]:
a1=np.arange(200).reshape(10,20)
print("\nArray is::-\n",a1)
print("\n Shape of the Array::-\n",a1.shape)
print("\n Size of the Array::-\n",a1.size)
print("\nDimension of the Array::-\n",a1.ndim)

a2=np.arange(200).reshape(5,40)
print("\nArray is::-\n",a2)
print("\n Shape of the Array::-\n",a2.shape)
print("\n Size of the Array::-\n",a2.size)
print("\nDimension of the Array::-\n",a2.ndim)

a3=np.arange(200).reshape(20,10)
print("\nArray is::-\n",a3)
print("\n Shape of the Array::-\n",a3.shape)
print("\n Size of the Array::-\n",a3.size)
print("\nDimension of the Array::-\n",a3.ndim)



Array is::-
 [[  0   1   2 ...  17  18  19]
 [ 20  21  22 ...  37  38  39]
 [ 40  41  42 ...  57  58  59]
 ...
 [140 141 142 ... 157 158 159]
 [160 161 162 ... 177 178 179]
 [180 181 182 ... 197 198 199]]

 Shape of the Array::-
 (10, 20)

 Size of the Array::-
 200

Dimension of the Array::-
 2

Array is::-
 [[  0   1   2 ...  37  38  39]
 [ 40  41  42 ...  77  78  79]
 [ 80  81  82 ... 117 118 119]
 [120 121 122 ... 157 158 159]
 [160 161 162 ... 197 198 199]]

 Shape of the Array::-
 (5, 40)

 Size of the Array::-
 200

Dimension of the Array::-
 2

Array is::-
 [[  0   1   2 ...   7   8   9]
 [ 10  11  12 ...  17  18  19]
 [ 20  21  22 ...  27  28  29]
 ...
 [170 171 172 ... 177 178 179]
 [180 181 182 ... 187 188 189]
 [190 191 192 ... 197 198 199]]

 Shape of the Array::-
 (20, 10)

 Size of the Array::-
 200

Dimension of the Array::-
 2


27. Question: Generate a large 2D array and demonstrate the use of np. reshape
() and unravel () to manipulate its shape for various linear algebra operations.

In [27]:
x=np.arange(16).reshape(4,4)
print(x)
x1=x.reshape(8,2)
print("\nReshape into another way::-\n",x1)
x2=x.reshape(2,8)
print("\nReshape into another way::-\n",x2)
x3=x.reshape(16,1)
print("\nReshape into another way::-\n",x3)
x.ravel()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Reshape into another way::-
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 ...
 [10 11]
 [12 13]
 [14 15]]

Reshape into another way::-
 [[ 0  1  2 ...  5  6  7]
 [ 8  9 10 ... 13 14 15]]

Reshape into another way::-
 [[ 0]
 [ 1]
 [ 2]
 ...
 [13]
 [14]
 [15]]


array([ 0,  1,  2, ..., 13, 14, 15])

28. Question: Given a 6x6 matrix, use advanced indexing and slicing to extract
the upper triangular part of the matrix and set the lower triangular part to zero.
Verify the result.

In [31]:
# Create a 6x6 matrix
A = np.arange(1, 37).reshape(6, 6)
print("Original Matrix:\n", A)

# Keep upper triangle and set lower triangle to zero
result = np.triu(A)

print("\nUpper triangular matrix:\n", result)


Original Matrix:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Upper triangular matrix:
 [[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]
